$id: CapabilityStatementRestSecurity
additionalProperties: false
description: Information about security of implementation. Information about security
  implementation from an interface perspective - what a client needs to know. [See
  https://hl7.org/fhir/R5/CapabilityStatementRestSecurity.html] [See https://hl7.org/fhir/R5/CapabilityStatementRestSecurity.html]
links: []
properties:
  _cors:
    $ref: FHIRPrimitiveExtension.yaml
    title: Extension field for ``cors``.
  _description:
    $ref: FHIRPrimitiveExtension.yaml
    title: Extension field for ``description``.
  cors:
    description: Server adds CORS headers when responding to requests - this enables
      Javascript applications to use the server.
    element_property: true
    title: Adds CORS Headers (http://enable-cors.org/)
    type: boolean
  description:
    element_property: true
    pattern: \s*(\S|\s)*
    title: General description of how security works
    type: string
  extension:
    description: May be used to represent additional information that is not part
      of the basic definition of the element. To make the use of extensions safe and
      managable, there is a strict set of governance applied to the definition and
      use of extensions. Though any implementer can define an extension, there is
      a set of requirements that SHALL be met as part of the definition of the extension.
    element_property: true
    items:
      $ref: Extension.yaml
    title: Additional content defined by implementations
    type: array
  fhir_comments:
    anyOf:
    - type: string
    - items:
        type: string
      type: array
    element_property: false
    title: Fhir Comments
  id:
    description: Unique id for the element within a resource (for internal references).
      This may be any string value that does not contain spaces.
    element_property: true
    pattern: '[ \r\n\t\S]+'
    title: Unique id for inter-element referencing
    type: string
  links:
    links:
      items:
        $ref: https://json-schema.org/draft/2020-12/links.yaml
      type: array
  modifierExtension:
    description: May be used to represent additional information that is not part
      of the basic definition of the element and that modifies the understanding of
      the element in which it is contained and/or the understanding of the containing
      element's descendants. Usually modifier elements provide negation or qualification.
      To make the use of extensions safe and managable, there is a strict set of governance
      applied to the definition and use of extensions. Though any implementer can
      define an extension, there is a set of requirements that SHALL be met as part
      of the definition of the extension. Applications processing a resource are required
      to check for modifier extensions.  Modifier extensions SHALL NOT change the
      meaning of any elements on Resource or DomainResource (including cannot change
      the meaning of modifierExtension itself).
    element_property: true
    items:
      $ref: Extension.yaml
    title: Extensions that cannot be ignored even if unrecognized
    type: array
  resourceType:
    const: CapabilityStatementRestSecurity
    default: CapabilityStatementRestSecurity
    description: One of the resource types defined as part of FHIR
    title: Resource Type
    type: string
  service:
    binding_description: Types of security services used with FHIR.
    binding_strength: extensible
    binding_uri: http://hl7.org/fhir/ValueSet/restful-security-service
    binding_version: null
    description: Types of security services that are supported/required by the system.
    element_property: true
    items:
      $ref: CodeableConcept.yaml
    title: OAuth | SMART-on-FHIR | NTLM | Basic | Kerberos | Certificates
    type: array
title: CapabilityStatementRestSecurity
type: object
