$id: Parameters
additionalProperties: false
description: Operation Request or Response. This resource is used to pass information
  into and back from an operation (whether invoked directly from REST or within a
  messaging environment).  It is not persisted or allowed to be referenced by other
  resources. [See https://hl7.org/fhir/R5/Parameters.html]
links:
- href: Reference/{id}
  rel: parameter_valueReference
  targetHints:
    backref:
    - parameters_parameter
    direction:
    - outbound
    multiplicity:
    - has_one
  targetSchema:
    $ref: Reference.yaml
  templatePointers:
    id: /parameter/-/valueReference/reference
  templateRequired:
  - id
properties:
  _implicitRules:
    $ref: FHIRPrimitiveExtension.yaml
    title: Extension field for ``implicitRules``.
  _language:
    $ref: FHIRPrimitiveExtension.yaml
    title: Extension field for ``language``.
  fhir_comments:
    anyOf:
    - type: string
    - items:
        type: string
      type: array
    element_property: false
    title: Fhir Comments
  id:
    description: The logical id of the resource, as used in the URL for the resource.
      Once assigned, this value never changes.
    element_property: true
    maxLength: 64
    minLength: 1
    pattern: ^[A-Za-z0-9\-.]+$
    title: Logical id of this artifact
    type: string
  implicitRules:
    description: A reference to a set of rules that were followed when the resource
      was constructed, and which must be understood when processing the content. Often,
      this is a reference to an implementation guide that defines the special rules
      along with other profiles etc.
    element_property: true
    pattern: \S*
    title: A set of rules under which this content was created
    type: string
  language:
    binding_description: IETF language tag for a human language
    binding_strength: required
    binding_uri: http://hl7.org/fhir/ValueSet/all-languages
    binding_version: 5.0.0
    description: The base language in which the resource is written.
    element_property: true
    pattern: ^[^\s]+(\s[^\s]+)*$
    title: Language of the resource content
    type: string
  links:
    links:
      items:
        $ref: https://json-schema.org/draft/2020-12/links.yaml
      type: array
  meta:
    $ref: Meta.yaml
    description: The metadata about the resource. This is content that is maintained
      by the infrastructure. Changes to the content might not always be associated
      with version changes to the resource.
    element_property: true
    title: Metadata about the resource
  parameter:
    description: A parameter passed to or received from the operation.
    element_property: true
    items:
      $ref: ParametersParameter.yaml
    title: Operation Parameter
    type: array
  resourceType:
    const: Parameters
    default: Parameters
    description: One of the resource types defined as part of FHIR
    title: Resource Type
    type: string
title: Parameters
type: object
