$id: ProductShelfLife
additionalProperties: false
description: The shelf-life and storage information for a medicinal product item or
  container can be described using this class. [See https://hl7.org/fhir/R5/ProductShelfLife.html]
  [See https://hl7.org/fhir/R5/ProductShelfLife.html]
links: []
properties:
  _periodString:
    $ref: FHIRPrimitiveExtension.yaml
    title: Extension field for ``periodString``.
  extension:
    description: May be used to represent additional information that is not part
      of the basic definition of the element. To make the use of extensions safe and
      managable, there is a strict set of governance applied to the definition and
      use of extensions. Though any implementer can define an extension, there is
      a set of requirements that SHALL be met as part of the definition of the extension.
    element_property: true
    items:
      $ref: Extension.yaml
    title: Additional content defined by implementations
    type: array
  fhir_comments:
    anyOf:
    - type: string
    - items:
        type: string
      type: array
    element_property: false
    title: Fhir Comments
  id:
    description: Unique id for the element within a resource (for internal references).
      This may be any string value that does not contain spaces.
    element_property: true
    pattern: '[ \r\n\t\S]+'
    title: Unique id for inter-element referencing
    type: string
  links:
    links:
      items:
        $ref: https://json-schema.org/draft/2020-12/links.yaml
      type: array
  modifierExtension:
    description: May be used to represent additional information that is not part
      of the basic definition of the element and that modifies the understanding of
      the element in which it is contained and/or the understanding of the containing
      element's descendants. Usually modifier elements provide negation or qualification.
      To make the use of extensions safe and managable, there is a strict set of governance
      applied to the definition and use of extensions. Though any implementer can
      define an extension, there is a set of requirements that SHALL be met as part
      of the definition of the extension. Applications processing a resource are required
      to check for modifier extensions.  Modifier extensions SHALL NOT change the
      meaning of any elements on Resource or DomainResource (including cannot change
      the meaning of modifierExtension itself).
    element_property: true
    items:
      $ref: Extension.yaml
    title: Extensions that cannot be ignored even if unrecognized
    type: array
  periodDuration:
    $ref: Duration.yaml
    element_property: true
    one_of_many: period
    one_of_many_required: false
    title: The shelf life time period can be specified using a numerical value for
      the period of time and its unit of time measurement The unit of measurement
      shall be specified in accordance with ISO 11240 and the resulting terminology
      The symbol and the symbol identifier shall be used
  periodString:
    element_property: true
    one_of_many: period
    one_of_many_required: false
    pattern: '[ \r\n\t\S]+'
    title: The shelf life time period can be specified using a numerical value for
      the period of time and its unit of time measurement The unit of measurement
      shall be specified in accordance with ISO 11240 and the resulting terminology
      The symbol and the symbol identifier shall be used
    type: string
  resourceType:
    const: ProductShelfLife
    default: ProductShelfLife
    description: One of the resource types defined as part of FHIR
    title: Resource Type
    type: string
  specialPrecautionsForStorage:
    element_property: true
    items:
      $ref: CodeableConcept.yaml
    title: Special precautions for storage, if any, can be specified using an appropriate
      controlled vocabulary The controlled term and the controlled term identifier
      shall be specified
    type: array
  type:
    $ref: CodeableConcept.yaml
    element_property: true
    title: This describes the shelf life, taking into account various scenarios such
      as shelf life of the packaged Medicinal Product itself, shelf life after transformation
      where necessary and shelf life after the first opening of a bottle, etc. The
      shelf life type shall be specified using an appropriate controlled vocabulary
      The controlled term and the controlled term identifier shall be specified
title: ProductShelfLife
type: object
