$id: ValueSetExpansionContainsPropertySubProperty
additionalProperties: false
description: SubProperty value for the concept. A subproperty value for this concept.
  [See https://hl7.org/fhir/R5/ValueSetExpansionContainsPropertySubProperty.html]
  [See https://hl7.org/fhir/R5/ValueSetExpansionContainsPropertySubProperty.html]
links: []
properties:
  _code:
    $ref: FHIRPrimitiveExtension.yaml
    title: Extension field for ``code``.
  _valueBoolean:
    $ref: FHIRPrimitiveExtension.yaml
    title: Extension field for ``valueBoolean``.
  _valueCode:
    $ref: FHIRPrimitiveExtension.yaml
    title: Extension field for ``valueCode``.
  _valueDateTime:
    $ref: FHIRPrimitiveExtension.yaml
    title: Extension field for ``valueDateTime``.
  _valueDecimal:
    $ref: FHIRPrimitiveExtension.yaml
    title: Extension field for ``valueDecimal``.
  _valueInteger:
    $ref: FHIRPrimitiveExtension.yaml
    title: Extension field for ``valueInteger``.
  _valueString:
    $ref: FHIRPrimitiveExtension.yaml
    title: Extension field for ``valueString``.
  code:
    description: A code that is a reference to ValueSet.expansion.property.code.
    element_property: true
    element_required: true
    pattern: ^[^\s]+(\s[^\s]+)*$
    title: Reference to ValueSet.expansion.property.code
    type: string
  extension:
    description: May be used to represent additional information that is not part
      of the basic definition of the element. To make the use of extensions safe and
      managable, there is a strict set of governance applied to the definition and
      use of extensions. Though any implementer can define an extension, there is
      a set of requirements that SHALL be met as part of the definition of the extension.
    element_property: true
    items:
      $ref: Extension.yaml
    title: Additional content defined by implementations
    type: array
  fhir_comments:
    anyOf:
    - type: string
    - items:
        type: string
      type: array
    element_property: false
    title: Fhir Comments
  id:
    description: Unique id for the element within a resource (for internal references).
      This may be any string value that does not contain spaces.
    element_property: true
    pattern: '[ \r\n\t\S]+'
    title: Unique id for inter-element referencing
    type: string
  links:
    links:
      items:
        $ref: https://json-schema.org/draft/2020-12/links.yaml
      type: array
  modifierExtension:
    description: May be used to represent additional information that is not part
      of the basic definition of the element and that modifies the understanding of
      the element in which it is contained and/or the understanding of the containing
      element's descendants. Usually modifier elements provide negation or qualification.
      To make the use of extensions safe and managable, there is a strict set of governance
      applied to the definition and use of extensions. Though any implementer can
      define an extension, there is a set of requirements that SHALL be met as part
      of the definition of the extension. Applications processing a resource are required
      to check for modifier extensions.  Modifier extensions SHALL NOT change the
      meaning of any elements on Resource or DomainResource (including cannot change
      the meaning of modifierExtension itself).
    element_property: true
    items:
      $ref: Extension.yaml
    title: Extensions that cannot be ignored even if unrecognized
    type: array
  resourceType:
    const: ValueSetExpansionContainsPropertySubProperty
    default: ValueSetExpansionContainsPropertySubProperty
    description: One of the resource types defined as part of FHIR
    title: Resource Type
    type: string
  valueBoolean:
    description: The value of this subproperty.
    element_property: true
    one_of_many: value
    one_of_many_required: true
    title: Value of the subproperty for this concept
    type: boolean
  valueCode:
    description: The value of this subproperty.
    element_property: true
    one_of_many: value
    one_of_many_required: true
    pattern: ^[^\s]+(\s[^\s]+)*$
    title: Value of the subproperty for this concept
    type: string
  valueCoding:
    $ref: Coding.yaml
    description: The value of this subproperty.
    element_property: true
    one_of_many: value
    one_of_many_required: true
    title: Value of the subproperty for this concept
  valueDateTime:
    description: The value of this subproperty.
    element_property: true
    format: date-time
    one_of_many: value
    one_of_many_required: true
    title: Value of the subproperty for this concept
    type: string
  valueDecimal:
    description: The value of this subproperty.
    element_property: true
    one_of_many: value
    one_of_many_required: true
    title: Value of the subproperty for this concept
    type: number
  valueInteger:
    description: The value of this subproperty.
    element_property: true
    one_of_many: value
    one_of_many_required: true
    title: Value of the subproperty for this concept
    type: integer
  valueString:
    description: The value of this subproperty.
    element_property: true
    one_of_many: value
    one_of_many_required: true
    pattern: '[ \r\n\t\S]+'
    title: Value of the subproperty for this concept
    type: string
title: ValueSetExpansionContainsPropertySubProperty
type: object
